"use client";

import { useMemo, useState } from "react";

type ArchiveItem = {
  id: string;
  module: string;
  type: string;
  title: string;
  original?: string;
  year: string;
  place?: string;
  summary: string;
  tags: string[];
  status: "已核实" | "部分核实" | "待核实";
  evidence: "A" | "B" | "C" | "D";
  source: string;
  sourceUrl?: string;
  publisher?: string;
  sourcePublishedAt?: string;
  relation?: string;
  evidenceStatement?: string;
  imageRights?: string;
  image: string;
};

const modules = [
  { id: "artists", no: "01", title: "艺术家与收藏", en: "Artists & Collection", desc: "影响过他的艺术家、作品与收藏线索", glyph: "人" },
  { id: "culture", no: "02", title: "电影、书籍与音乐", en: "Films, Books & Music", desc: "他公开提到、看过、读过或听过的作品", glyph: "文" },
  { id: "tmi", no: "03", title: "日常兴趣与习惯", en: "Daily Life", desc: "骑行、阅读、植物与舞台之外的生活片段", glyph: "日" },
  { id: "music", no: "04", title: "个人音乐作品", en: "Solo Music", desc: "从早期作品到个人专辑、单曲与合作曲目", glyph: "音" },
  { id: "interviews", no: "05", title: "采访与公开谈话", en: "Interviews & Talks", desc: "关于音乐、艺术、成长与身份的公开表达", glyph: "言" },
  { id: "exhibitions", no: "06", title: "看过的展览", en: "Exhibitions Visited", desc: "公开记录中出现过的美术馆与展览", glyph: "展" },
  { id: "sfmoma", no: "07", title: "RM × SFMOMA 特展", en: "RM × SFMOMA", desc: "2026 年在旧金山展开的收藏对话", glyph: "间" },
];

const items: ArchiveItem[] = [
  { id:"artist-001", module:"artists", type:"绘画", title:"尹亨根", original:"Yun Hyong-keun · 윤형근", year:"1928–2007", place:"韩国", summary:"韩国单色画的重要艺术家。RM 在《Indigo》时期明确谈到尹亨根的生平、作品与创作观对自己的启发；这种关联也进入专辑歌曲《Yun》。", tags:["明确启发","单色画","Indigo"], status:"已核实", evidence:"A", relation:"明确欣赏 / 创作启发", source:"Vogue：RM on Artistry, Collaboration, and His First Solo Album, ‘Indigo’", sourceUrl:"https://www.vogue.com/article/rm-bts-indigo-interview", publisher:"Vogue", sourcePublishedAt:"2022-12-02", evidenceStatement:"RM 直接说明尹亨根的坚持、人生经历与作品如何启发自己，并解释《Indigo》与歌曲《Yun》的关联。", imageRights:"未使用人物或作品图；字母占位。后续仅采用艺术家基金会、画廊或展馆授权素材。", image:"Y" },
  { id:"artist-002", module:"artists", type:"绘画 / 雕塑", title:"李禹焕", original:"Lee Ufan · 이우환", year:"1936–", place:"韩国 / 日本", summary:"跨越单色画与物派语境的艺术家。RM 曾去釜山看他的展，也在访客簿里写下自己对《风》系列的喜欢。", tags:["喜欢《风》系列","单色画","物派"], status:"已核实", evidence:"B", relation:"看过展，也喜欢《风》系列", source:"Yonhap：BTS leader RM's special love of Korean paintings", sourceUrl:"https://en.yna.co.kr/view/AEN20191015005200315", publisher:"Yonhap News Agency", sourcePublishedAt:"2019-10-15", evidenceStatement:"报道引用展馆提供的访客簿记录：RM 表示喜欢李禹焕的《风》系列；该证据支持对具体系列的喜爱，不扩展为全部作品。", imageRights:"新闻图片标注 PHOTO NOT FOR SALE，本站不使用；保留版权安全占位。", image:"L" },
  { id:"artist-003", module:"artists", type:"绘画", title:"金焕基", original:"Kim Whanki · 김환기", year:"1913–1974", place:"韩国 / 美国", summary:"韩国现代艺术家，以抽象绘画与点画作品著称。RM 不止一次走进有金焕基作品的展览，那些安静的蓝与点仿佛也很适合他的世界。", tags:["多次观展","韩国现代艺术","点画"], status:"部分核实", evidence:"B", relation:"不止一次看过他的作品", source:"Yonhap：BTS leader RM's special love of Korean paintings", sourceUrl:"https://en.yna.co.kr/view/AEN20191015005200315", publisher:"Yonhap News Agency", sourcePublishedAt:"2019-10-15", evidenceStatement:"可核实部分是 RM 参观过两场包含金焕基作品的展览；“favorite”来自记者的谨慎推断，并非 RM 在该文中的直接表述。", imageRights:"报道所载社交媒体照片标注 PHOTO NOT FOR SALE，本站不使用。", image:"K" },
  { id:"artist-004", module:"artists", type:"建筑 / 家具设计", title:"乔治·中岛", original:"George Nakashima", year:"1905–1990", place:"美国", summary:"以尊重木材自然形态的家具设计闻名。RM 在采访中谈到家具收藏时，直接称乔治·中岛是自己的最爱。", tags:["明确最喜欢","家具设计","木作"], status:"已核实", evidence:"A", relation:"明确称为最喜欢", source:"EL PAÍS：RM, the leader of K-pop band BTS…", sourceUrl:"https://english.elpais.com/culture/2023-03-15/rm-the-leader-of-k-pop-band-bts-we-work-so-hard-in-korea-because-70-years-ago-there-was-nothing.html", publisher:"EL PAÍS English", sourcePublishedAt:"2023-03-15", evidenceStatement:"在谈及家具收藏时，RM 直接说自己喜爱 Charlotte Perriand 与 Pierre Jeanneret，而最喜欢的是 George Nakashima。", imageRights:"未使用设计作品照片；后续需获得 Nakashima Foundation 或权利方许可。", image:"N" },
  { id:"artist-005", module:"artists", type:"建筑 / 家具设计", title:"夏洛特·佩里安", original:"Charlotte Perriand", year:"1903–1999", place:"法国", summary:"法国现代主义建筑师与设计师。RM 在谈及家具收藏与审美取向时，明确表示自己喜爱她的作品。", tags:["明确喜欢","现代主义","家具设计"], status:"已核实", evidence:"A", relation:"明确表示喜欢", source:"EL PAÍS：RM, the leader of K-pop band BTS…", sourceUrl:"https://english.elpais.com/culture/2023-03-15/rm-the-leader-of-k-pop-band-bts-we-work-so-hard-in-korea-because-70-years-ago-there-was-nothing.html", publisher:"EL PAÍS English", sourcePublishedAt:"2023-03-15", evidenceStatement:"RM 直接表示自己喜爱 Charlotte Perriand 与 Pierre Jeanneret；证据来自问答原文。", imageRights:"未使用人物或设计作品图；字母占位，许可状态待权利方确认。", image:"P" },
  { id:"artist-006", module:"artists", type:"建筑 / 家具设计", title:"皮埃尔·让纳雷", original:"Pierre Jeanneret", year:"1896–1967", place:"瑞士 / 法国", summary:"建筑师与现代家具设计师，长期参与昌迪加尔项目。RM 在同一采访中明确表示喜爱他的作品。", tags:["明确喜欢","现代主义","家具设计"], status:"已核实", evidence:"A", relation:"明确表示喜欢", source:"EL PAÍS：RM, the leader of K-pop band BTS…", sourceUrl:"https://english.elpais.com/culture/2023-03-15/rm-the-leader-of-k-pop-band-bts-we-work-so-hard-in-korea-because-70-years-ago-there-was-nothing.html", publisher:"EL PAÍS English", sourcePublishedAt:"2023-03-15", evidenceStatement:"RM 直接表示自己喜爱 Charlotte Perriand 与 Pierre Jeanneret；本站不将“喜欢”扩大为“最喜欢”。", imageRights:"未使用人物或设计作品图；字母占位，许可状态待权利方确认。", image:"J" },
  { id:"artist-007", module:"artists", type:"当代艺术", title:"村上隆", original:"Takashi Murakami · 村上隆", year:"1962–", place:"日本", summary:"日本当代艺术家。RM 曾聊起自己收藏村上隆玩具的时期，鲜艳、奇异又带一点童心，是他的收藏故事里很可爱的一页。", tags:["收藏","当代艺术","玩具"], status:"已核实", evidence:"A", relation:"收藏过他的玩具", source:"EL PAÍS：RM, the leader of K-pop band BTS…", sourceUrl:"https://english.elpais.com/culture/2023-03-15/rm-the-leader-of-k-pop-band-bts-we-work-so-hard-in-korea-because-70-years-ago-there-was-nothing.html", publisher:"EL PAÍS English", sourcePublishedAt:"2023-03-15", evidenceStatement:"RM 说自己曾收藏 Takashi Murakami figures。该陈述仅支持收藏关系。", imageRights:"未使用艺术家角色或作品图，以避免角色形象与作品版权风险。", image:"M" },
  { id:"artist-008", module:"artists", type:"当代艺术", title:"罗尼·霍恩", original:"Roni Horn", year:"1955–", place:"美国", summary:"她的雕塑、摄影与文字总在身份和自然之间来回流动。RM 想过，有一天把她的作品带进自己梦想中的小小展览空间。", tags:["想放进未来的展","观念艺术","跨媒介"], status:"已核实", evidence:"A", relation:"想把她的作品带进未来的空间", source:"EL PAÍS：RM, the leader of K-pop band BTS…", sourceUrl:"https://english.elpais.com/culture/2023-03-15/rm-the-leader-of-k-pop-band-bts-we-work-so-hard-in-korea-because-70-years-ago-there-was-nothing.html", publisher:"EL PAÍS English", sourcePublishedAt:"2023-03-15", evidenceStatement:"RM 表示未来希望把 Roni Horn 等艺术家的作品带到自己设想的空间；这证明策展兴趣，不等于收藏或最爱。", imageRights:"未使用作品图片；后续须由艺术家工作室、画廊或展馆确认许可。", image:"R" },
  { id:"artist-009", module:"artists", type:"绘画", title:"张旭镇", original:"Chang Ucchin · 장욱진", year:"1917–1990", place:"韩国", summary:"韩国现代画家，常用简练的构图画人物、树木与日常。RM 的收藏里也有他的作品，朴拙又安静，很像一首短短的诗。", tags:["RM的收藏","韩国现代艺术","日常"], status:"已核实", evidence:"A", relation:"收藏了他的作品", source:"SFMOMA：RM x SFMOMA Press Release", sourceUrl:"https://d1hhug17qm51in.cloudfront.net/www-media/2025/10/20103112/RM-x-SFMOMA_Press-Release_Updated-5-20-26.pdf", publisher:"San Francisco Museum of Modern Art", sourcePublishedAt:"2026-05-20", evidenceStatement:"SFMOMA 官方新闻稿将 Chang Ucchin 列为 RM 收藏中的韩国现代与当代艺术重要人物；这不自动等于“最喜欢”。", imageRights:"新闻稿未为本站授予作品图使用权；继续使用字母占位。", image:"C" },
  { id:"culture-001", module:"culture", type:"电影", title:"分手的决心", original:"Decision to Leave · 헤어질 결심", year:"2022", place:"韩国", summary:"朴赞郁执导的爱情悬疑电影。RM 一遍遍走进影院，后来甚至看到了第八遍；《Closer》也曾与电影画面合作，像是两种忧郁在海雾里相遇。", tags:["看过八遍","朴赞郁","Closer"], status:"已核实", evidence:"B", relation:"反复观看，也聊过自己喜欢它的理由", source:"Finally, Park Chan-wook：RM interview", sourceUrl:"https://btsinterviews.wordpress.com/2023/02/22/01-23-finally-park-chanwook-with-namjoon/", publisher:"Finally, Park Chan-wook / interview archive", sourcePublishedAt:"2023-01", image:"D" },
  { id:"culture-002", module:"culture", type:"电影", title:"南汉山城", original:"The Fortress · 남한산성", year:"2017", place:"韩国", summary:"发生在丙子胡乱时期的历史电影。RM 喜欢它没有急着给出简单答案，也被人物在现实利益与心中价值之间的拉扯触动。", tags:["他喜欢的电影","历史","价值与选择"], status:"已核实", evidence:"B", relation:"看完后认真分享过感受", source:"Soompi：BTS's RM Talks About Films And Books With Fans", sourceUrl:"https://www.soompi.com/article/1074523wpp/btss-rm-talks-films-books-fans", publisher:"Soompi", sourcePublishedAt:"2017-11-10", image:"城" },
  { id:"culture-003", module:"culture", type:"电影", title:"雷神3：诸神黄昏", original:"Thor: Ragnarok", year:"2017", place:"美国", summary:"一部色彩明亮、节奏飞快的超级英雄电影。RM 在 IMAX 看完后开心地聊起洛基，说电影很好玩——这一格就保留那种轻松的喜欢。", tags:["看过的电影","Marvel","Loki"], status:"已核实", evidence:"B", relation:"看完觉得很有趣，也很喜欢洛基", source:"Soompi：BTS's RM Talks About Films And Books With Fans", sourceUrl:"https://www.soompi.com/article/1074523wpp/btss-rm-talks-films-books-fans", publisher:"Soompi", sourcePublishedAt:"2017-11-10", image:"T" },
  { id:"culture-004", module:"culture", type:"书籍", title:"少年来了", original:"Human Acts · 소년이 온다", year:"2014", place:"韩国", summary:"韩江以多重声音写下光州的创伤与记忆。RM 在去欧洲的飞机和酒店里读完它，说文字好得让自己感到压倒性的震动。", tags:["读过的书","韩江","记忆"], status:"已核实", evidence:"B", relation:"读完后说它带来了很深的震动", source:"Soompi：BTS's RM Talks About Films And Books With Fans", sourceUrl:"https://www.soompi.com/article/1074523wpp/btss-rm-talks-films-books-fans", publisher:"Soompi", sourcePublishedAt:"2017-11-10", image:"少" },
  { id:"culture-005", module:"culture", type:"书籍", title:"82年生的金智英", original:"Kim Jiyoung, Born 1982 · 82년생 김지영", year:"2016", place:"韩国", summary:"赵南柱写下一位普通女性生命里那些常被忽略的细小裂缝。RM 曾和《少年来了》一起提到它，说两本书都让自己产生了许多感受。", tags:["读过的书","赵南柱","女性经验"], status:"已核实", evidence:"B", relation:"读过，也分享过它带来的感受", source:"Soompi：BTS's RM Talks About Films And Books With Fans", sourceUrl:"https://www.soompi.com/article/1074523wpp/btss-rm-talks-films-books-fans", publisher:"Soompi", sourcePublishedAt:"2017-11-10", image:"82" },
  { id:"culture-006", module:"culture", type:"书籍", title:"请照顾好我妈妈", original:"Please Look After Mom · 엄마를 부탁해", year:"2008", place:"韩国", summary:"申京淑从一位母亲的失踪写回家庭记忆与迟到的理解。这本小说出现在 RM 被整理出的喜欢与推荐书目中，也陪许多粉丝走进韩国文学。", tags:["书单","申京淑","家庭"], status:"部分核实", evidence:"C", relation:"出现在他的喜欢与推荐书目中", source:"The Daily Star：Five of BTS leader RM’s favourite books", sourceUrl:"https://www.thedailystar.net/daily-star-books/news/five-bts-leader-rms-favourite-books-3069391", publisher:"The Daily Star", sourcePublishedAt:"2022-07-15", image:"母" },
  { id:"culture-007", module:"culture", type:"音乐", title:"Elliott Smith", original:"ELLIOTT SMITH", year:"1969–2003", place:"美国", summary:"低声、脆弱又锋利的唱作世界。RM 说自己那段时间一直在听 Elliott Smith；这些音乐也悄悄进入《Bicycle》的气息里。", tags:["正在听","唱作人","Bicycle"], status:"已核实", evidence:"A", relation:"聆听他的音乐，并影响《Bicycle》的氛围", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"E" },
  { id:"culture-008", module:"culture", type:"音乐", title:"Jeff Buckley", original:"JEFF BUCKLEY", year:"1966–1997", place:"美国", summary:"他的声音像从很深的地方升起来。RM 把 Jeff Buckley 列入当时一直在听、也影响自己生活与音乐的人之中。", tags:["正在听","摇滚","Bicycle"], status:"已核实", evidence:"A", relation:"聆听他的音乐，并带进自己的创作感受", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"J" },
  { id:"culture-009", module:"culture", type:"音乐", title:"KIRINJI", original:"キリンジ", year:"1996–", place:"日本", summary:"日本乐队 KIRINJI 的旋律游走在 city pop、灵魂乐与流行之间。RM 在谈《Bicycle》时，也把他们放进那份影响自己生活的近期歌单。", tags:["正在听","日本音乐","Bicycle"], status:"已核实", evidence:"A", relation:"近期聆听，也影响《Bicycle》的音乐气息", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"K" },
  { id:"culture-010", module:"culture", type:"音乐", title:"Radiohead / Portishead", original:"TWO DOORS INTO ALTERNATIVE MUSIC", year:"1990s–", place:"英国", summary:"一个在摇滚、电子与焦虑之间不断变形，一个把阴影、节拍与人声织成夜色。RM 曾把 Radiohead 与 Portishead 和 Nas、Eminem 一起说成影响自己的音乐。", tags:["音乐影响","英国另类音乐","声音世界"], status:"已核实", evidence:"A", relation:"亲口提到的音乐影响", source:"EL PAÍS：RM, the leader of K-pop band BTS…", sourceUrl:"https://english.elpais.com/culture/2023-03-15/rm-the-leader-of-k-pop-band-bts-we-work-so-hard-in-korea-because-70-years-ago-there-was-nothing.html", publisher:"EL PAÍS English", sourcePublishedAt:"2023-03-15", image:"R/P" },
  { id:"tmi-001", module:"tmi", type:"日常", title:"骑自行车", original:"BICYCLE DAYS", year:"长期兴趣", place:"公园与城市骑行", summary:"骑车时，他觉得自己暂时摆脱了应该如何感受、如何思考的压力。风吹起来的那一刻，也是他最接近身心自由的时候。", tags:["自行车","自由","Bicycle"], status:"已核实", evidence:"A", relation:"长期喜欢的日常活动，也写成了歌曲《Bicycle》", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"自" },
  { id:"tmi-002", module:"tmi", type:"周末", title:"美术馆、公园、骑行", original:"A QUIET WEEKEND", year:"2021", place:"不记录具体路线", summary:"如果有属于自己的周末，他常在美术馆、公园和自行车之间选择。后来粉丝也把这种安静看展、亲近自然的生活方式叫作“Namjooning”。", tags:["美术馆","公园","Namjooning"], status:"已核实", evidence:"A", relation:"他分享过的周末方式", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"周" },
  { id:"tmi-003", module:"tmi", type:"日常", title:"一个人走去书店", original:"THE BOOKSTORE WALK", year:"2021", place:"社区书店", summary:"他会独自步行去附近的大书店，一边挑书，一边想自己究竟是怎样的人。即使书店里很热闹，每个人都低头看书的状态仍让他感到自由。", tags:["书店","散步","独处"], status:"已核实", evidence:"A", relation:"会特意留出时间逛书店和阅读", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"书" },
  { id:"tmi-004", module:"tmi", type:"习惯", title:"随时都可以读书", original:"READ, ANYWHERE", year:"长期习惯", place:"工作与生活间隙", summary:"化妆时、吃饭时、和成员们待在一起时，他都可能翻开一本书。《In the SOOP》里的许多安静镜头，也留下了他阅读的样子。", tags:["阅读","书籍","随身习惯"], status:"已核实", evidence:"A", relation:"把阅读放进生活里的很多空隙", source:"Weverse Magazine：RM’s Bibilly Hills", sourceUrl:"https://magazine.weverse.io/article/view/632?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2023-01-17", image:"R" },
  { id:"tmi-005", module:"tmi", type:"植物", title:"有名字的盆栽朋友", original:"BABY PLUM · JJINJJIN · CHERRY · ORI", year:"2019–", place:"工作室与家中", summary:"他的盆栽不只是摆设：红梅 Baby Plum、杜松 Jjinjjin、樱树 Cherry、枫树 Ori 都有自己的名字。他会浇水、说话，也从照顾生命这件事里照看自己。", tags:["盆栽","植物","四个名字"], status:"已核实", evidence:"A", relation:"长期照顾并为盆栽取名", source:"Weverse Magazine：RM’s Bibilly Hills", sourceUrl:"https://magazine.weverse.io/article/view/632?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2023-01-17", image:"植" },
  { id:"tmi-006", module:"tmi", type:"空间", title:"不断变化的 Rkive", original:"MON STUDIO → RKIVE", year:"出道后至今", place:"个人工作室", summary:"工作室像一张不断更新的兴趣地图：早期摆满 KAWS 玩偶，后来逐渐出现尹亨根的画、George Nakashima 的木家具、雕塑和盆栽。", tags:["工作室","室内布置","Rkive"], status:"已核实", evidence:"A", relation:"会随着兴趣变化重新布置自己的空间", source:"Weverse Magazine：RM’s Bibilly Hills", sourceUrl:"https://magazine.weverse.io/article/view/632?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2023-01-17", image:"室" },
  { id:"tmi-007", module:"tmi", type:"兴趣", title:"一边品饮，一边阅读", original:"WHISKEY & READING", year:"2022–2023", place:"个人时间", summary:"对威士忌产生兴趣后，他不只品饮，也会同时读相关书籍。喜欢一件事，就顺着它继续学习，这很像他进入每个兴趣世界的方式。", tags:["威士忌","阅读","深入了解"], status:"已核实", evidence:"A", relation:"会在品饮时阅读相关知识", source:"Weverse Magazine：RM’s Bibilly Hills", sourceUrl:"https://magazine.weverse.io/article/view/632?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2023-01-17", image:"W" },
  { id:"tmi-008", module:"tmi", type:"习惯", title:"一周运动四次", original:"FOUR TIMES A WEEK", year:"2020–2021", place:"日常训练", summary:"他曾分享自己坚持一周运动四次。吸引他的并不只是结果，而是能够感受到自己正在一点一点变得更好。", tags:["运动","规律","进步感"], status:"已核实", evidence:"A", relation:"曾长期保持每周四次的运动节奏", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"4×" },
  { id:"tmi-009", module:"tmi", type:"小收藏", title:"宝可梦与快龙", original:"POKÉMON · DRAGONITE", year:"2018–2022", place:"游戏与收藏", summary:"提到宝可梦时，他曾兴奋地支持快龙，还和 Jin 在练习途中跑去抓 Pokémon GO 里的快龙。后来晒出的宝可梦面包贴纸，也延续了这份童心。", tags:["宝可梦","快龙","Pokémon GO"], status:"部分核实", evidence:"B", relation:"喜欢宝可梦，也对快龙格外兴奋", source:"ComicBook：BTS Inspires New Wave of Pokémon Masters", sourceUrl:"https://comicbook.com/anime/news/pokemon-anime-bts-dragonite-mangnanyong-reaction/", publisher:"ComicBook", sourcePublishedAt:"2018-10-12", image:"龙" },
  { id:"tmi-010", module:"tmi", type:"音乐瞬间", title:"用萨克斯迎接 Jin", original:"DYNAMITE ON SAXOPHONE", year:"2024-06-12", place:"公开迎接场合", summary:"Jin 完成兵役的那天，RM 带着萨克斯出现，用《Dynamite》的旋律迎接他。没有长篇台词，只有一个有点郑重、又非常可爱的重逢方式。", tags:["萨克斯","Dynamite","重逢"], status:"已核实", evidence:"B", relation:"曾公开用萨克斯演奏《Dynamite》", source:"The Independent：RM plays Dynamite on saxophone", sourceUrl:"https://www.independent.co.uk/tv/culture/bts-jin-military-rm-saxophone-b2561248.html", publisher:"The Independent", sourcePublishedAt:"2024-06-12", image:"SAX" },
  { id:"music-001", module:"music", type:"Mixtape", title:"RM", original:"1ST MIXTAPE · 11 TRACKS", year:"2015-03-20", place:"Seoul", summary:"锋利、年轻、几乎不留退路的第一张个人 mixtape。从《Voice》到《Do You》《Joke》，他把那时必须说出口的话，一口气写进十一首歌里。", tags:["完整作品","Mixtape","Do You"], status:"已核实", evidence:"B", relation:"第一张个人 mixtape", source:"BANGTAN BLOG：RM mixtape", sourceUrl:"https://btsblog.ibighit.com/285", publisher:"BANGTAN BLOG", sourcePublishedAt:"2015-03-20", image:"RM" },
  { id:"music-002", module:"music", type:"Mixtape", title:"mono.", original:"PLAYLIST · 7 TRACKS", year:"2018-10-23", place:"Seoul / Tokyo / Moonlight", summary:"七首歌像一场从夜晚走到清晨的散步。城市、孤独、雨与告别被放进克制的灰色声场，最后落在《forever rain》的雨里。", tags:["完整作品","Mixtape","forever rain"], status:"已核实", evidence:"A", relation:"第二张个人 mixtape，也被称作 playlist", source:"BTS SoundCloud：RM - mono.", sourceUrl:"https://soundcloud.com/bangtan/sets/rm-mono-2018", publisher:"BTS / SoundCloud", sourcePublishedAt:"2018-10-23", image:"m." },
  { id:"music-003", module:"music", type:"单曲", title:"Bicycle", original:"BICYCLE", year:"2021-06-07", place:"Seoul", summary:"踩下踏板时，快乐和一点点寂寞同时出现。RM 与 John Eun 共同创作，把骑行时短暂而真实的自由写成一首温柔的歌。", tags:["单曲","FESTA","John Eun"], status:"已核实", evidence:"A", relation:"作词、作曲与演唱", source:"Yonhap：RM unveils self-written solo song Bicycle", sourceUrl:"https://en.yna.co.kr/view/AEN20210607002800315", publisher:"Yonhap News Agency", sourcePublishedAt:"2021-06-07", image:"BI" },
  { id:"music-004", module:"music", type:"专辑", title:"Indigo", original:"1ST SOLO ALBUM · 10 TRACKS", year:"2022-12-02", place:"A LAST ARCHIVE OF MY TWENTIES", summary:"第一张正式个人专辑，也是他二十代最后的档案。艺术、城市、关系与自我被铺成十种颜色，Erykah Badu、Anderson .Paak、Tablo、Youjeen 等音乐人共同走进这片靛蓝。", tags:["完整作品","专辑","Wild Flower"], status:"已核实", evidence:"A", relation:"首张正式个人专辑", source:"BIGHIT MUSIC：Indigo", sourceUrl:"https://bts.ibighit.com/eng/discography/rm/detail/indigo/", publisher:"BIGHIT MUSIC", sourcePublishedAt:"2022-12-02", image:"IN" },
  { id:"music-005", module:"music", type:"单曲", title:"Wild Flower", original:"들꽃놀이 · WITH YOUJEEN", year:"2022-12-02", place:"Indigo · Track 09", summary:"他没有选择瞬间绚烂的烟火，而是想成为安静盛开的野花。Youjeen 穿透云层般的声音，让这首歌在辽阔与孤独之间不断抬升。", tags:["单曲","Indigo","Youjeen"], status:"已核实", evidence:"A", relation:"主打歌 · 与 Youjeen 合作", source:"BIGHIT MUSIC：Indigo", sourceUrl:"https://bts.ibighit.com/eng/discography/rm/detail/indigo/", publisher:"BIGHIT MUSIC", sourcePublishedAt:"2022-12-02", image:"野" },
  { id:"music-006", module:"music", type:"合作", title:"Still Life", original:"WITH ANDERSON .PAAK", year:"2022-12-02", place:"Indigo · Track 02", summary:"静物也仍然活着。轻快的节奏、铜管与 Anderson .Paak 的声音一起向前推，让“被框住”不再等于停止生长。", tags:["合作","Indigo","Anderson .Paak"], status:"已核实", evidence:"A", relation:"与 Anderson .Paak 合作", source:"BIGHIT MUSIC：Indigo", sourceUrl:"https://bts.ibighit.com/eng/discography/rm/detail/indigo/", publisher:"BIGHIT MUSIC", sourcePublishedAt:"2022-12-02", image:"SL" },
  { id:"music-007", module:"music", type:"专辑", title:"Right Place, Wrong Person", original:"2ND SOLO ALBUM · 11 TRACKS", year:"2024-05-24", place:"THE WRONG PLACE", summary:"第二张正式个人专辑把“不合时宜”的感觉推到最前面。另类、爵士、摇滚与 hip-hop 在十一首歌里碰撞，粗粝、幽默、迷路，也比以往更自由。", tags:["完整作品","专辑","RPWP"], status:"已核实", evidence:"A", relation:"第二张正式个人专辑", source:"BIGHIT MUSIC：Right Place, Wrong Person", sourceUrl:"https://bts.ibighit.com/eng/discography/rm/detail/rpwp/", publisher:"BIGHIT MUSIC", sourcePublishedAt:"2024-05-24", image:"RP" },
  { id:"music-008", module:"music", type:"单曲", title:"Come back to me", original:"PRE-RELEASE SINGLE", year:"2024-05-10", place:"Right Place, Wrong Person · Track 11", summary:"一句“回来吧”被放进不断变化的人生房间。OHHYUK 参与创作与编曲，落日飞车的 Kuo 带来吉他与贝斯，歌声最终回到柔软的呼吸里。", tags:["单曲","RPWP","OHHYUK"], status:"已核实", evidence:"A", relation:"先行单曲 · 专辑收尾曲", source:"RM ‘Come back to me’ Official MV", sourceUrl:"https://www.youtube.com/watch?v=NrfikKxF4Ps", publisher:"BANGTANTV", sourcePublishedAt:"2024-05-10", image:"CB" },
  { id:"music-009", module:"music", type:"单曲", title:"LOST!", original:"TITLE TRACK", year:"2024-05-24", place:"Right Place, Wrong Person · Track 08", summary:"迷路并不总是坏事。明亮又错位的 synth、快速切换的情绪与玩心十足的影像，把困惑唱成继续寻找出口的动力。", tags:["单曲","RPWP","主打歌"], status:"已核实", evidence:"A", relation:"专辑主打歌", source:"RM ‘LOST!’ Official MV", sourceUrl:"https://www.youtube.com/watch?v=kq6UVL3H6SI", publisher:"BANGTANTV", sourcePublishedAt:"2024-05-24", image:"L!" },
  { id:"music-010", module:"music", type:"合作", title:"Domodachi", original:"FEAT. LITTLE SIMZ", year:"2024-05-24", place:"Right Place, Wrong Person · Track 04", summary:"鼓点、萨克斯与近乎即兴的段落把两位 rapper 推进同一个不稳定空间。Little Simz 的 verse 落下之后，这场古怪又漂亮的同行继续向前。", tags:["合作","RPWP","Little Simz"], status:"已核实", evidence:"A", relation:"与 Little Simz 合作", source:"BIGHIT MUSIC：Right Place, Wrong Person", sourceUrl:"https://bts.ibighit.com/eng/discography/rm/detail/rpwp/", publisher:"BIGHIT MUSIC", sourcePublishedAt:"2024-05-24", image:"友" },
  { id:"interview-001", module:"interviews", type:"音乐创作", title:"我常常思考，现在的自己走到了哪里", original:"WEVERSE MAGAZINE · BE COMEBACK INTERVIEW", year:"2020-11-28", place:"Seoul", summary:"从《BE》的制作方式聊到工作、责任与二十代。这里的他一边回望那些矛盾又炽热的年月，一边承认：越靠近 BTS，越难用一句话定义 BTS。", tags:["音乐创作","BE","二十代"], status:"已核实", evidence:"A", relation:"一次关于位置、责任与成长的长谈", source:"Weverse Magazine：RM — I spend a lot of time thinking about where I am now", sourceUrl:"https://magazine.weverse.io/article/view/62?category=1&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2020-11-28", image:"20" },
  { id:"interview-002", module:"interviews", type:"日常与成长", title:"希望自己正在去往某个地方", original:"WEVERSE MAGAZINE · BUTTER INTERVIEW", year:"2021-07-30", place:"Seoul", summary:"他谈写歌时的停滞，也谈骑车、看展、运动和一个人走去书店。读到最后，会发现那些安静的日常不是离开音乐，而是他慢慢找回自己的路。", tags:["日常与成长","Butter","Namjooning"], status:"已核实", evidence:"A", relation:"从快速运转的生活里寻找自己的节奏", source:"Weverse Magazine：RM — I hope I’m on my way somewhere", sourceUrl:"https://magazine.weverse.io/article/view/213?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2021-07-30", image:"→" },
  { id:"interview-003", module:"interviews", type:"BTS", title:"The Triumph of BTS", original:"ROLLING STONE COVER STORY", year:"2021-05-14", place:"Seoul", summary:"一次属于七个人的封面长谈。RM 说起跨越语言与文化边界的意义，也认真面对成功背后的阴影、排外与少数群体的处境。", tags:["BTS","全球文化","身份"], status:"已核实", evidence:"A", relation:"关于 BTS、世界与“局外人”的群体采访", source:"Rolling Stone：The Triumph of BTS", sourceUrl:"https://www.rollingstone.com/music/music-features/bts-band-cover-story-new-music-2021-1167277/", publisher:"Rolling Stone", sourcePublishedAt:"2021-05-14", image:"RS" },
  { id:"interview-004", module:"interviews", type:"音乐创作", title:"艺术家必须成为独一无二的自己", original:"WEVERSE MAGAZINE · PROOF INTERVIEW", year:"2022-06-19", place:"Seoul", summary:"《Proof》把过去摆在眼前，也把“接下来呢”这个问题留给他。RM 从《Yet To Come》聊到创作方向，想继续寻找只属于自己的声音。", tags:["音乐创作","Proof","未来"], status:"已核实", evidence:"A", relation:"回望九年，也想象下一阶段", source:"Weverse Magazine：You have to be the one and only", sourceUrl:"https://magazine.weverse.io/article/view/438?artist=BTS&lang=en", publisher:"Weverse Magazine", sourcePublishedAt:"2022-06-19", image:"1/1" },
  { id:"interview-005", module:"interviews", type:"艺术", title:"Intersections：RM 与艺术", original:"THE ART BASEL PODCAST · S02 E01", year:"2022-06-28", place:"Art Basel Podcast", summary:"从第一次买下作品，到美术馆如何改变巡演间隙的时间。他谈收藏、韩国艺术、创作者的生命，也描绘过一个任何人都能走进去看作品的未来空间。", tags:["艺术","收藏","美术馆"], status:"已核实", evidence:"A", relation:"第一次完整以英语进行的播客对谈", source:"Art Basel：Intersections — RM (Leader, BTS)", sourceUrl:"https://podcasts.apple.com/us/podcast/intersections-the-art-basel-podcast/id1576271279", publisher:"Art Basel", sourcePublishedAt:"2022-06-28", image:"AB" },
  { id:"interview-006", module:"interviews", type:"艺术", title:"把艺术当作观看世界的镜头", original:"ARTNEWS · A CONVERSATION WITH RM", year:"2022-07-26", place:"Seoul", summary:"关于为什么看展、如何开始收藏，也关于不必害怕“不懂”。他更在意作品带来的身体感受：停下来，走近一点，再让自己的眼睛决定。", tags:["艺术","收藏","看展"], status:"已核实", evidence:"B", relation:"一次面向艺术世界的个人采访", source:"ARTnews：BTS’s RM Talks About His Growing Influence and Appreciation of Art", sourceUrl:"https://www.artnews.com/art-news/news/bts-rm-interview-art-collector-1234635198/", publisher:"ARTnews", sourcePublishedAt:"2022-07-26", image:"ART" },
  { id:"interview-007", module:"interviews", type:"音乐创作", title:"Indigo 记录了我作为人与艺术家的成长", original:"VOGUE · INDIGO INTERVIEW", year:"2022-12-02", place:"Seoul", summary:"十首歌，十种颜色，也是一段二十代的收尾。他细说每首歌为什么需要不同的声音，以及尹亨根、合作音乐人与“成为人之后再谈艺术”如何进入《Indigo》。", tags:["音乐创作","Indigo","合作"], status:"已核实", evidence:"A", relation:"围绕首张正式个人专辑的完整对谈", source:"Vogue：RM on Creativity, Collaboration, and Indigo", sourceUrl:"https://www.vogue.com/article/rm-bts-indigo-interview", publisher:"Vogue", sourcePublishedAt:"2022-12-02", image:"V" },
  { id:"interview-008", module:"interviews", type:"音乐创作", title:"追寻不会轻易褪色的东西", original:"NME · INDIGO INTERVIEW", year:"2022-12-02", place:"Seoul", summary:"如果《mono.》像流动的夜，《Indigo》更像一本摊开的日记。RM 谈三年创作期里的犹疑、转向和选择，也谈自己为什么开始在意“经得住时间”的作品。", tags:["音乐创作","Indigo","时间"], status:"已核实", evidence:"A", relation:"关于《Indigo》与 timelessness 的深谈", source:"NME：RM talks Indigo and the pursuit of timelessness", sourceUrl:"https://www.nme.com/features/bts-rm-interview-indigo-3356430", publisher:"NME", sourcePublishedAt:"2022-12-02", image:"NME" },
  { id:"interview-009", module:"interviews", type:"日常与成长", title:"在 RM 与 Kim Namjoon 之间", original:"EL PAÍS · A LONG CONVERSATION", year:"2023-03-15", place:"Madrid / Seoul", summary:"一场直接而辽阔的谈话：K-pop、韩国近代经验、工作强度、艺术收藏、不同身份，以及成为三十岁的人。他没有把复杂问题变成漂亮答案。", tags:["日常与成长","韩国文化","身份"], status:"已核实", evidence:"A", relation:"关于文化、职业与个人身份的长篇采访", source:"EL PAÍS：RM, the leader of K-pop band BTS", sourceUrl:"https://english.elpais.com/culture/2023-03-15/rm-the-leader-of-k-pop-band-bts-we-work-so-hard-in-korea-because-70-years-ago-there-was-nothing.html", publisher:"EL PAÍS", sourcePublishedAt:"2023-03-15", image:"EP" },
  { id:"interview-010", module:"interviews", type:"影像", title:"Right People, Wrong Place：打开门说话", original:"DOCUMENTARY INTERVIEW #1 · INTRO", year:"2024-11-19", place:"BANGTANTV", summary:"这段采访像纪录片入口：他想把 2023 年沉浸、思考和喜爱过的一切留下，也让 RM 与 Kim Namjoon 第一次一起走到镜头前。", tags:["影像","RPWP","纪录片"], status:"已核实", evidence:"A", relation:"纪录片采访系列的开场", source:"BANGTANTV：RM — Right People, Wrong Place Interview #1", sourceUrl:"https://www.youtube.com/watch?v=zj162UQjwFo", publisher:"BANGTANTV", sourcePublishedAt:"2024-11-19", image:"REC" },
  { id:"exhibition-001", module:"exhibitions", type:"绘画 / 影像", title:"David Hockney", original:"DAVID HOCKNEY · SOLO EXHIBITION", year:"2019", place:"首尔 · 首尔市立美术馆", summary:"明亮的泳池、不断变化的观看角度和跨越媒介的创作，构成这场韩国首次大型 David Hockney 个展。它也成为早期“沿着 RM 去看展”的热门一站。", tags:["首尔","David Hockney","SeMA"], status:"部分核实", evidence:"B", relation:"公开分享过参观记录", source:"Seoul Metropolitan Government：David Hockney Exhibition", sourceUrl:"https://english.seoul.go.kr/seoul-museum-of-art-david-hockney-exhibition/", publisher:"Seoul Metropolitan Government", sourcePublishedAt:"2019-03-29", image:"DH" },
  { id:"exhibition-002", module:"exhibitions", type:"绘画 / 雕塑", title:"Space Lee Ufan", original:"LEE UFAN AND HIS WORKS", year:"2019-06", place:"釜山 · 釜山市立美术馆", summary:"在由安藤忠雄参与设计的空间里，石、铁板、画布与留白彼此回应。RM 在访客簿留下文字，也写下自己对《风》系列的喜欢。", tags:["釜山","李禹焕","Space Lee Ufan"], status:"已核实", evidence:"A", relation:"参观并在访客簿留言", source:"Busan Metropolitan City：BTS Member RM Visits Busan Museum of Art", sourceUrl:"https://www.busan.go.kr/eng/bsnews01/1520316", publisher:"Busan Metropolitan City", sourcePublishedAt:"2022-02-14", image:"風" },
  { id:"exhibition-003", module:"exhibitions", type:"绘画", title:"Kim Chong-hak：Highlighting Contemporary Artist III", original:"김종학 · 설악산의 화가", year:"2020-05", place:"釜山 · 釜山市立美术馆", summary:"被称为“雪岳山画家”的金宗学，把山野、花草和季节压进浓烈色彩。RM 再次来到釜山市立美术馆，也让更多人跟着走进这片繁盛的自然。", tags:["釜山","Kim Chong-hak","自然"], status:"已核实", evidence:"A", relation:"公开确认的展览参观记录", source:"Busan Metropolitan City：BTS Member RM Visits Busan Museum of Art", sourceUrl:"https://www.busan.go.kr/eng/bsnews01/1520316", publisher:"Busan Metropolitan City", sourcePublishedAt:"2022-02-14", image:"山" },
  { id:"exhibition-004", module:"exhibitions", type:"美术馆收藏", title:"Dia Beacon", original:"A FIRST VISIT TO DIA BEACON", year:"2021-12", place:"美国 · Beacon, New York", summary:"旧工厂般辽阔的空间里，光线和作品一起缓慢移动。第一次参观后，他后来又回到这里完成《Indigo》现场表演，让美术馆与音乐真正接在一起。", tags:["美国","Dia Beacon","Indigo"], status:"已核实", evidence:"A", relation:"2021 年首次参观，后来在此录制现场", source:"Dia Art Foundation：RM Live in New York at Dia Beacon", sourceUrl:"https://diaart.org/media/watch-listen/rm-live-in-new-york-at-dia-beacon", publisher:"Dia Art Foundation", sourcePublishedAt:"2022-12", image:"DIA" },
  { id:"exhibition-005", module:"exhibitions", type:"美术馆收藏", title:"Glenstone Museum", original:"ART · ARCHITECTURE · LANDSCAPE", year:"2021-12", place:"美国 · Potomac, Maryland", summary:"建筑、风景与当代艺术被放在同一种安静里。他在橡树下留下照片，并写下“Ucchin vibe”——自然中的片刻，也让人想起张旭镇画里的树。", tags:["美国","Glenstone","张旭镇"], status:"已核实", evidence:"B", relation:"休假期间参观并公开分享", source:"Chosun：RM’s art journey in the United States", sourceUrl:"https://www.chosun.com/national/weekend/2021/12/18/J2JJD5SSFNBT3GRP6FZBQKLNP4/", publisher:"The Chosun Ilbo", sourcePublishedAt:"2021-12-18", image:"GL" },
  { id:"exhibition-006", module:"exhibitions", type:"绘画 / 雕塑", title:"Calder–Picasso", original:"CALDER–PICASSO", year:"2021-12", place:"美国 · Museum of Fine Arts, Houston", summary:"Calder 的平衡与 Picasso 的形体在同一展览里对望。RM 的参观记录把这场关于线条、空间与运动的双人展带进了许多人的旅行清单。", tags:["美国","Calder","Picasso"], status:"部分核实", evidence:"B", relation:"公开分享过展览参观照片", source:"The Chosun Ilbo：RM’s U.S. art journey", sourceUrl:"https://www.chosun.com/national/weekend/2021/12/18/J2JJD5SSFNBT3GRP6FZBQKLNP4/", publisher:"The Chosun Ilbo", sourcePublishedAt:"2021-12-18", image:"C/P" },
  { id:"exhibition-007", module:"exhibitions", type:"雕塑", title:"Kwon Jin Kyu Centennial：Angel of Atelier", original:"권진규 탄생 100주년 기념", year:"2022-03", place:"首尔 · 首尔市立美术馆", summary:"一场为雕塑家权镇圭百年诞辰而作的回望。RM 收藏的《Horse》也曾借展其中；他走进展厅，像是去看一件熟悉作品回到更大的生命脉络。", tags:["首尔","Kwon Jin Kyu","雕塑"], status:"已核实", evidence:"B", relation:"参观展览，并借出个人收藏作品", source:"Seoul Museum of Art：Kwon Jin Kyu Centennial", sourceUrl:"https://sema.seoul.go.kr/en/whatson/exhibition/detail?exNo=1175274&glolangType=ENG", publisher:"Seoul Museum of Art", sourcePublishedAt:"2022", image:"馬" },
  { id:"exhibition-008", module:"exhibitions", type:"雕塑 / 装置", title:"Jean-Michel Othoniel：Treasure Gardens", original:"TREASURE GARDENS", year:"2022-07", place:"首尔 · 德寿宫 / 首尔市立美术馆", summary:"镜面珠串、花朵与宫殿花园彼此映照。RM 在盛夏走进这座“宝藏花园”，传统空间与当代雕塑也在他的镜头里短暂相遇。", tags:["首尔","Othoniel","德寿宫"], status:"部分核实", evidence:"B", relation:"公开分享过参观记录", source:"Perrotin / Ocula：Jean-Michel Othoniel, Treasure Gardens", sourceUrl:"https://static.perrotin.com/pdf/press_review/2023_08_23_ocula_jean_michel_othoniel_on_the_disturbed_geometry_of_gardens_10272.pdf", publisher:"Ocula / Perrotin", sourcePublishedAt:"2022-06", image:"花" },
  { id:"exhibition-009", module:"exhibitions", type:"装置 / 影像", title:"Philippe Parreno：VOICES", original:"필립 파레노 · 보이스", year:"2024-03", place:"首尔 · Leeum 美术馆", summary:"展览像有自己的意识：灯光、声音、影像与漂浮的鱼不断改变空间。RM 分享的参观片段，也让这场流动、难以被固定的展览进入他的艺术地图。", tags:["首尔","Philippe Parreno","Leeum"], status:"已核实", evidence:"B", relation:"公开分享过展览参观记录", source:"Leeum Museum of Art：Philippe Parreno — VOICES", sourceUrl:"https://www.leeumhoam.org/leeum/exhibition/76?params=Y", publisher:"Leeum Museum of Art", sourcePublishedAt:"2024-02-28", image:"声" },
  { id:"exhibition-010", module:"exhibitions", type:"雕塑 / 绘画", title:"Kim Yun Shin", original:"김윤신 · KUKJE GALLERY", year:"2024-03", place:"首尔 · Kukje Gallery", summary:"木头被劈开、连接，再长成新的结构；绘画也延续着“合与分”的节奏。RM 在同一周末分享这场个展，与一位长期往返韩国和阿根廷的艺术家相遇。", tags:["首尔","Kim Yun Shin","Kukje Gallery"], status:"已核实", evidence:"B", relation:"公开分享过展览参观记录", source:"Kukje Gallery：Kim Yun Shin Solo Exhibition", sourceUrl:"https://www.kukjegallery.com/upload/press/_Kukje_Gallery__Kim_Yun_Shin_Solo_Exhibition__Kim_Yun_Shin_.pdf", publisher:"Kukje Gallery", sourcePublishedAt:"2024-03-19", image:"合" },
];

const timeline = ["1994", "2013", "2015", "2018", "2022", "2024", "NOW"];

const archiveNotes: Record<string, string> = {
  artists: "这一部分整理了 RM 公开谈到、收藏或曾在展览中关注过的艺术家。不同记录所能确认的关系并不相同，因此分别标注为喜欢、收藏、观展或创作影响。",
  culture: "电影、书籍和音乐构成了他的文化参照。这里收录公开采访与分享中出现过的作品，并保留作品首次发表或被提及的时间。",
  tmi: "骑行、阅读、植物和看展等日常习惯，呈现了舞台之外较为安静的一面。内容以公开采访与影像记录为基础。",
  music: "从早期作品、mixtape 到正式个人专辑与合作曲目，这条时间线呈现了其创作语言的变化。它是一份入门索引，并非完整曲目表。",
  interviews: "这些采访围绕音乐创作、艺术收藏、成长与身份展开，按发布时间整理，便于观察他在不同阶段的表达。",
  exhibitions: "这一部分按时间与地点整理公开出现过的展览参观记录，并区分参观、分享及作品借展等不同关系。",
  search: "可按人物、作品、年份、地点或关键词查找档案内容。"
};

const musicJourney = [
  { year:"2007—2014", title:"早期与出道阶段", works:"出道前作品 · Intro: O!RUL8,2? · Monterlude · Intro: What Am I to You", note:"早期作品已经出现关于身份、野心与自我证明的主题，表达直接而密集。" },
  { year:"2015", title:"Mixtape《RM》", works:"Voice · Do You · Awakening · Joke · Monster", note:"这张作品集中保留了早期锋利、竞争性强的说唱表达，也记录了当时的自我定位。" },
  { year:"2016—2017", title:"个人曲与合作", works:"Reflection · Always · Change · 4 O’Clock", note:"作品开始更直接地讨论孤独、不安、社会变化与人与人之间的关系。" },
  { year:"2018", title:"Mixtape《mono.》", works:"tokyo · seoul · moonchild · everythingoes · forever rain", note:"七首作品以城市、夜晚与情绪流动为线索，形成了更克制、连贯的声音空间。" },
  { year:"2018—2021", title:"个人曲、合作与单曲", works:"Trivia 承: Love · Timeless · Crying Over You · Winter Flower · Strange · Don’t · Bicycle", note:"不同类型的合作扩展了声音边界，《Bicycle》则把骑行与自由感写进个人创作。" },
  { year:"2022", title:"专辑《Indigo》", works:"Yun · Still Life · Closer · Wild Flower · No.2", note:"专辑汇集艺术、关系、疲惫与成长等主题，也被视为其二十代创作阶段的一次整理。" },
  { year:"2022—2023", title:"合作作品", works:"SEXY NUKIM · Smoke Sprite · Don’t ever say love me", note:"与不同音乐人的合作继续探索另类流行、独立摇滚和韩国说唱等声音方向。" },
  { year:"2024", title:"《Right Place, Wrong Person》", works:"Come back to me · Nuts · Domodachi · Groin · LOST!", note:"专辑进一步转向更自由的编排和视觉叙事，并围绕错位感、自我认知与关系展开。" }
];

type WatchEntry = { year:string; kind:string; title:string; description:string; query:string };
const bilibiliSearch = (query:string) => `https://search.bilibili.com/all?keyword=${encodeURIComponent(query)}`;

const musicWatchlist: WatchEntry[] = [
  { year:"2007—2014", kind:"EARLY WORKS", title:"出道前作品与早期个人曲", description:"从 Runch Randa 时期的作品整理，到《Intro: O!RUL8,2?》《Monterlude》与《Intro: What Am I to You》。", query:"金南俊 出道前 单曲 合作曲 Runch Randa 合集" },
  { year:"2015", kind:"MIXTAPE · 11 TRACKS", title:"《RM》与三支 MV", description:"可从《Awakening》《Do You》《Joke》的影像开始，再寻找现场表演与制作花絮。", query:"RM mixtape 2015 Awakening Do You Joke MV 中字" },
  { year:"2016—2017", kind:"SONGS & COLLABORATIONS", title:"《Reflection》到《4 O’Clock》", description:"包括《Always》《Change》《Gajah》《4 O’Clock》与《Champion (Remix)》等个人曲、合作与现场资料。", query:"RM Reflection Always Change 4 O'Clock 中字 合集" },
  { year:"2018", kind:"PLAYLIST · 7 TRACKS", title:"《mono.》完整播放清单", description:"《moonchild》《seoul》《forever rain》等七首作品，以及专辑发布后的制作分享。", query:"RM mono 完整专辑 moonchild seoul forever rain 中字" },
  { year:"2018—2021", kind:"SOLO & FEATURES", title:"个人曲、合作与纪念单曲", description:"从《Trivia 承: Love》《Intro: Persona》，听到《Winter Flower》《Strange》《Don’t》与《Bicycle》。", query:"RM Trivia Love Persona Winter Flower Strange Don't Bicycle 中字" },
  { year:"2022", kind:"ALBUM · 10 TRACKS", title:"《Indigo》影像与现场", description:"收录《Wild Flower》《Still Life》《Hectic》《No.2》的影像线索，并延伸到 Dia Beacon、Rolling Hall 与专辑幕后。", query:"RM Indigo Wild Flower Still Life Dia Beacon Rolling Hall 中字" },
  { year:"2022—2023", kind:"FEATURES", title:"跨风格合作", description:"《SEXY NUKIM》《Smoke Sprite》《Don’t ever say love me》把说唱、独立与另类流行接在一起。", query:"RM Sexy Nukim Smoke Sprite Don't ever say love me 中字" },
  { year:"2024", kind:"ALBUM · 11 TRACKS", title:"《Right Place, Wrong Person》影像索引", description:"从《Come back to me》《LOST!》《Groin》《Nuts》《Domodachi》到纪录片与 Mini & Moni Music。", query:"RM Right Place Wrong Person Come back to me LOST Groin Domodachi 中字" },
  { year:"2024", kind:"FEATURES", title:"《Neva Play》与其他合作", description:"继续补充专辑之外的合作作品，作为个人音乐时间线的支线。", query:"RM Neva Play Megan Thee Stallion 中字" }
];

const everydayWatchlist: WatchEntry[] = [
  { year:"2013—2016", kind:"LOG", title:"早期 LOG 合集", description:"练习、创作与阶段性想法的短记录，适合按发布时间慢慢观看。", query:"金南俊 RM 出道至今 log 合集 中字" },
  { year:"2019—", kind:"LIVE", title:"专辑制作与回归直播", description:"围绕作品写作、编曲、合作和发布过程的长谈。", query:"金南俊 专辑制作 直播 behind 合集 中字" },
  { year:"2019", kind:"VLOG", title:"城市漫步与看展记录", description:"从成员个人 VLOG 开始，观察他在旅行、展览与日常中的节奏。", query:"BTS VLOG RM 金南俊 2019 中字" },
  { year:"2022", kind:"VLOG", title:"RM 美术馆 VLOG", description:"沿着一次美术馆参观，观看艺术、建筑与城市如何进入他的日常。", query:"BTS VLOG RM 美术馆 2022 中字" },
  { year:"2022", kind:"ALL DAY", title:"All Day with RM", description:"以两部分影像记录《Indigo》时期的一天，包含工作与生活片段。", query:"RM All Day with 金南俊 Part 1 Part 2 中字" },
  { year:"2022", kind:"LIVE PERFORMANCE", title:"《Indigo》空间现场", description:"Dia Beacon 与 Rolling Hall 的现场让专辑和不同空间发生联系。", query:"RM Indigo Dia Beacon Rolling Hall live 中字" }
];

const interviewWatchlist: WatchEntry[] = [
  { year:"2022", kind:"INTERVIEW", title:"RM × Pharrell Williams", description:"围绕音乐创作、团队经验与个人阶段展开的长篇对谈。", query:"RM Pharrell Williams Rolling Stone interview 中字" },
  { year:"2022", kind:"TALK SHOW", title:"PSICK SHOW：RM 篇", description:"更轻松的谈话形式，内容涉及英文表达、音乐与日常。", query:"PSICK SHOW RM 金南俊 完整 中字" },
  { year:"2024", kind:"ALBUM TALK", title:"Mini & Moni Music：交换专辑", description:"围绕《Right Place, Wrong Person》的创作与聆听感受展开交流。", query:"Mini Moni Music RM Right Place Wrong Person 中字" },
  { year:"2024", kind:"DOCUMENTARY", title:"Right People, Wrong Place", description:"与第二张正式个人专辑同期完成的纪录片及采访内容。", query:"RM Right People Wrong Place documentary 中字" },
  { year:"合集", kind:"VARIETY & TALK", title:"综艺与长谈索引", description:"将较长的节目和采访集中为补充入口，便于从不同侧面继续了解。", query:"金南俊 RM 综艺 采访 长篇 合集 中字" }
];

export default function Home() {
  const [active, setActive] = useState("home");
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("全部状态");
  const [selected, setSelected] = useState<ArchiveItem | null>(null);
  const [menu, setMenu] = useState(false);

  const filtered = useMemo(() => items.filter((item) => {
    const moduleMatch = active === "home" || active === "search" || active === item.module;
    const text = `${item.type} ${item.title} ${item.original || ""} ${item.summary} ${item.tags.join(" ")} ${item.place || ""}`.toLowerCase();
    return moduleMatch && (!query || text.includes(query.toLowerCase())) && (status === "全部状态" || item.status === status);
  }), [active, query, status]);

  const go = (id: string) => {
    setActive(id); setMenu(false); setQuery(""); window.setTimeout(() => window.scrollTo({ top: 0, behavior: "smooth" }), 0);
  };

  return <main id="content">
    <a className="skip" href="#content">跳至主要内容</a>
    <header className="topbar">
      <button className="brand" onClick={() => go("home")} aria-label="返回首页"><span>RM</span><b>ARCHIVE</b></button>
      <nav className={menu ? "nav open" : "nav"} aria-label="一级模块">
        {modules.map(m => <button key={m.id} onClick={() => go(m.id)} className={active === m.id ? "active" : ""}><small>{m.no}</small>{m.en}</button>)}
      </nav>
      <div className="tools"><button onClick={() => setActive("search")} aria-label="打开搜索">⌕</button><button className="lang" aria-label="切换语言">中 / EN</button><button className="menubtn" onClick={() => setMenu(!menu)} aria-label="打开导航">{menu ? "×" : "☰"}</button></div>
    </header>

    {active === "home" && <section className="hero tree-hero">
      <div className="tree-noise" aria-hidden="true"></div>
      <div className="tree-title"><div className="eyebrow">KIM NAMJOON / DIGITAL ARCHIVE / 2026</div><h1><span>RM</span><i>ARCHIVE</i></h1></div>
      <div className="tree-stage" aria-label="七个档案模块的树形导航">
        <img src="/archive-tree.png" alt="实验拼贴风格的档案树" />
        {modules.map((m,i)=><button key={m.id} className={`branch-label branch-${i+1}`} onClick={()=>go(m.id)}><span>{m.no}</span><b>{m.title}</b><small>{m.en}</small></button>)}
        <div className="tree-stamp" aria-hidden="true">07 /<br/>SECTIONS</div>
      </div>
      <div className="tree-bottom"><div className="searchbox"><span>⌕</span><input value={query} onChange={e => {setQuery(e.target.value); setActive("search")}} placeholder="SEARCH THE ARCHIVE" aria-label="全站搜索"/><kbd>↵</kbd></div></div>
    </section>}

    {active === "home" ? <>
      <section className="statement personal-statement"><span className="misprint">RM / KIM NAMJOON<br/>1994 — NOW</span><small>A DIGITAL ARCHIVE OF MUSIC, ART AND WORDS</small><h2>从作品与公开记录出发，<br/><i>认识 RM，也认识金南俊。</i></h2><p>这里整理他的个人音乐、采访、文化兴趣、艺术收藏与展览足迹。内容按主题与时间组织，呈现一位音乐人如何在持续创作中观察自己，也如何通过艺术、阅读和日常经验理解世界。</p><div className="statement-tags"><span>ART</span><span>WORDS</span><span>MUSIC</span><span>PLACE</span><span>TIME</span></div></section>
      <section className="modules-section">
        <div className="section-head"><div><small>COLLECTIONS · 07</small><h2>探索档案</h2></div></div>
        <div className="module-grid">{modules.map((m, i) => <button className={`module-card c${i+1}`} key={m.id} onClick={() => go(m.id)}><div className="card-top"><span>{m.no}</span><b>{m.glyph}</b></div><div><small>{m.en}</small><h3>{m.title}</h3></div><i>↗</i></button>)}</div>
      </section>
      <section className="timeline-section"><div className="section-head light"><div><small>CHRONOLOGY</small><h2>时间索引</h2></div></div><div className="timeline">{timeline.map((t,i)=><div key={t} className={i===timeline.length-1?"now":""}><span></span><b>{t}</b><small>{i===0?"BEGIN":i===timeline.length-1?"CONTINUING":"ARCHIVE"}</small></div>)}</div></section>
      <section className="featured"><div className="section-head"><div><small>A FEW PLACES TO BEGIN</small><h2>可以从这里开始</h2></div><button onClick={() => setActive("search")}>慢慢逛全部 ↗</button></div><ArchiveGrid data={items.filter(item=>["music-004","artist-004","culture-002"].includes(item.id))} onSelect={setSelected}/></section>
    </> : active === "sfmoma" ? <SfmomaView onHome={() => go("home")}/> : <ArchiveView
      active={active} query={query} setQuery={setQuery} status={status} setStatus={setStatus}
      data={filtered} onSelect={setSelected} onHome={() => go("home")}
    />}

    <footer><div className="footer-brand"><span>RM</span><b>ARCHIVE</b></div><div><b>七个部分</b>{modules.map(m=><button key={m.id} onClick={()=>go(m.id)}>{m.title}</button>)}</div><div><b>导航</b><button onClick={()=>go("artists")}>艺术家与收藏</button><button onClick={()=>go("music")}>个人音乐作品</button><button onClick={()=>go("exhibitions")}>看过的展览</button><button onClick={()=>go("sfmoma")}>07 · RM × SFMOMA</button></div><div className="footer-note"><span>2026</span></div></footer>

    {selected && <Detail item={selected} onClose={() => setSelected(null)}/>}
  </main>;
}

function SfmomaView({onHome}:{onHome:()=>void}) {
  return <section className="sfmoma-view" aria-labelledby="sfmoma-title">
    <button className="back-home" onClick={onHome}><span>←</span> 回到主界面 <small>BACK TO THE TREE</small></button>
    <div className="sfmoma-hero">
      <div className="sfmoma-intro"><small>07 · SPECIAL EXHIBITION / SAN FRANCISCO</small><p>2026.10.03 — 2027.02.07</p><h2 id="sfmoma-title">RM <i>×</i><br/>SFMOMA</h2><span>BETWEEN YOU AND ME</span></div>
      <div className="sfmoma-orbit" aria-hidden="true"><span>YOU</span><b>×</b><span>ME</span></div>
    </div>
    <div className="sfmoma-marquee"><span>一场关于艺术、收藏与相遇的展览</span><span>FLOOR 7 · SAN FRANCISCO</span></div>
    <div className="sfmoma-story"><div><small>THE EXHIBITION</small><h3>在他的收藏里，<br/>与世界相遇。</h3></div><p>这是首场展出 RM 私人收藏作品的美术馆展览。约 200 件来自 RM 与 SFMOMA 收藏的作品并置，让韩国现当代艺术与世界各地的艺术在同一空间展开对话。</p></div>
    <div className="sfmoma-facts"><div><small>01 / WHEN</small><b>10.03 — 02.07</b><span>2026 — 2027</span></div><div><small>02 / WHERE</small><b>SFMOMA</b><span>旧金山现代艺术博物馆 · 7 楼</span></div><div><small>03 / WORKS</small><b>200</b><span>来自 RM 与 SFMOMA 的收藏</span></div></div>
    <div className="sfmoma-collections"><header><small>IN CONVERSATION</small><h3>两份收藏，<br/><i>一场对话。</i></h3></header><div className="sfmoma-collection-list"><div><small>RM COLLECTION · 部分参展艺术家</small><p>尹亨根 · 朴崍贤 · 权玉渊 · 金允信 · 都相凤 · 张旭镇</p></div><div><small>SFMOMA COLLECTION · 官方列举的对话作品艺术家</small><p>金焕基 · 马克·罗斯科 · 艾格尼丝·马丁 · 亨利·马蒂斯 · 乔治娅·欧姬芙 · 保罗·克利</p></div></div></div>
    <div className="sfmoma-visit"><div><small>PLAN YOUR VISIT</small><h3>去看见，<br/>它如何发生。</h3><p>展览位于 SFMOMA 7 楼。参观需要提前在官方渠道预约「RM x SFMOMA + General Admission」定时门票；普通门票不包含本展入场。票价与余票可能变化，请以馆方页面为准。</p></div><div className="sfmoma-actions"><a href="https://www.sfmoma.org/exhibition/rm-x-sfmoma/" target="_blank" rel="noopener noreferrer">展览官方页面 <span>↗</span></a><a href="https://www.sfmoma.org/visit/rm-x-sfmoma-between-you-and-me-faq/" target="_blank" rel="noopener noreferrer">门票与参观 FAQ <span>↗</span></a></div></div>
  </section>;
}

function ArchiveView({active,query,setQuery,status,setStatus,data,onSelect,onHome}:{active:string;query:string;setQuery:(s:string)=>void;status:string;setStatus:(s:string)=>void;data:ArchiveItem[];onSelect:(i:ArchiveItem)=>void;onHome:()=>void}) {
  const mod = modules.find(m=>m.id===active);
  const isMap = active === "exhibitions";
  return <section className="archive-view">
    <button className="back-home" onClick={onHome}><span>←</span> 回到主界面 <small>BACK TO THE TREE</small></button>
    <div className="archive-title"><small>{active === "search" ? "LOOK AROUND" : `${mod?.no} · ${mod?.en.toUpperCase()}`}</small><h2>{active === "search" ? "想找什么？" : mod?.title}</h2><p className="archive-letter">{archiveNotes[active]}</p></div>
    {active === "culture" && <div className="culture-tabs compact-tabs"><button onClick={()=>setQuery("")}>全部 · 10</button><button onClick={()=>setQuery("电影")}>电影 · 03</button><button onClick={()=>setQuery("书籍")}>书籍 · 03</button><button onClick={()=>setQuery("音乐")}>音乐 · 04</button></div>}
    {active === "tmi" && <><EverydayWindows/><WatchShelf eyebrow="VIDEO NOTES" title="从这些影像继续看" intro="这里集中放置 LOG、直播、VLOG 与空间现场。链接进入 B 站搜索结果，可根据字幕、画质与发布时间自行选择版本。" entries={everydayWatchlist}/><div className="culture-tabs compact-tabs"><button onClick={()=>setQuery("")}>全部 · 10</button><button onClick={()=>setQuery("自行车")}>骑行</button><button onClick={()=>setQuery("阅读")}>阅读</button><button onClick={()=>setQuery("植物")}>植物</button><button onClick={()=>setQuery("音乐")}>音乐</button></div></>}
    {active === "music" && <><MusicJourney/><WatchShelf eyebrow="LISTEN & WATCH" title="按时间找到作品" intro="从早期作品到两张正式个人专辑，这里补充 MV、现场、幕后与合作曲的观看入口。不是完整曲库，而是一条更容易进入的路线。" entries={musicWatchlist}/><div className="music-archive-label"><small>SELECTED STORIES</small><h3>再从这些作品里，挑几首慢慢听</h3></div><div className="culture-tabs compact-tabs"><button onClick={()=>setQuery("")}>全部 · 10</button><button onClick={()=>setQuery("完整作品")}>完整作品</button><button onClick={()=>setQuery("单曲")}>单曲</button><button onClick={()=>setQuery("合作")}>合作</button></div></>}
    {active === "interviews" && <><WatchShelf eyebrow="WATCH & LISTEN" title="采访与节目入口" intro="长访谈、专辑对谈与纪录片被放在一起，作为文字档案之外的补充观看路径。" entries={interviewWatchlist}/><div className="culture-tabs compact-tabs"><button onClick={()=>setQuery("")}>全部 · 10</button><button onClick={()=>setQuery("音乐创作")}>音乐创作 · 04</button><button onClick={()=>setQuery("日常与成长")}>成长 · 02</button><button onClick={()=>setQuery("艺术")}>艺术 · 02</button><button onClick={()=>setQuery("BTS")}>BTS</button><button onClick={()=>setQuery("影像")}>影像</button></div></>}
    {active === "exhibitions" && <div className="culture-tabs compact-tabs"><button onClick={()=>setQuery("")}>全部 · 10</button><button onClick={()=>setQuery("首尔")}>首尔 · 05</button><button onClick={()=>setQuery("釜山")}>釜山 · 02</button><button onClick={()=>setQuery("美国")}>美国 · 03</button></div>}
    <div className="filterbar"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="输入关键词"/></label><button onClick={()=>{setQuery("");setStatus("全部状态")}}>清除</button></div>
    <div className="result-head"><span>这里有 {data.length.toString().padStart(2,"0")} 篇记录</span></div>
    {isMap && <MapPanel data={data} onSelect={onSelect}/>} 
    {data.length ? <ArchiveGrid data={data} onSelect={onSelect}/> : <div className="empty"><b>没有找到匹配内容</b><p>尝试更换关键词或清除筛选。</p></div>}
  </section>
}

function MusicJourney() {
  return <section className="music-journey" aria-labelledby="music-journey-title"><div className="music-journey-head"><small>A LISTENING GUIDE · NOT A COMPLETE DISCOGRAPHY</small><h3 id="music-journey-title">沿着音乐，<br/><i>认识他。</i></h3></div><div className="music-journey-list">{musicJourney.map((stop,index)=><article key={stop.year}><span>{String(index+1).padStart(2,"0")}</span><time>{stop.year}</time><div><h4>{stop.title}</h4><b>{stop.works}</b><p>{stop.note}</p></div></article>)}</div></section>;
}

function EverydayWindows() {
  const windows = [
    ["LIVE · 2019—", "专辑制作直播", "作品发布前后进行的直播常涉及编曲、歌词、合作过程与制作取舍，是了解专辑背景的重要补充。"],
    ["LOG · 2013—2016", "早期成长记录", "出道初期的短片保存了练习、工作与阶段性思考，也呈现了创作方式逐渐形成的过程。"],
    ["VLOG · 2019—", "看展、旅行与日常", "美术馆参观、城市旅行和骑行等影像，记录了工作之外的兴趣与生活节奏。"],
    ["TALK · 2022—", "采访与谈话节目", "相关谈话从音乐、艺术延伸至文化与身份，呈现他在不同时期对相同问题的重新思考。"]
  ];
  return <section className="everyday-windows"><header><small>ANOTHER WAY TO KNOW HIM</small><h3>不只在舞台上。</h3></header><div>{windows.map(([label,title,copy])=><article key={label}><span>{label}</span><h4>{title}</h4><p>{copy}</p></article>)}</div></section>;
}

function WatchShelf({eyebrow,title,intro,entries}:{eyebrow:string;title:string;intro:string;entries:WatchEntry[]}) {
  return <section className="watch-shelf"><header><div><small>{eyebrow}</small><h3>{title}</h3></div><p>{intro}</p></header><div className="watch-list">{entries.map((entry,index)=><a key={`${entry.year}-${entry.title}`} href={bilibiliSearch(entry.query)} target="_blank" rel="noreferrer"><span className="watch-index">{String(index+1).padStart(2,"0")}</span><div className="watch-copy"><div><time>{entry.year}</time><small>{entry.kind}</small></div><h4>{entry.title}</h4><p>{entry.description}</p></div><b>在 B 站查找 ↗</b></a>)}</div></section>;
}

function ArchiveGrid({data,onSelect}:{data:ArchiveItem[];onSelect:(i:ArchiveItem)=>void}) { return <div className="archive-grid">{data.map(item=><article key={item.id} className="archive-card" onClick={()=>onSelect(item)}><div className="thumb"><span aria-hidden="true">{item.image}</span><img src={`/illustrations/${item.id}.webp`} alt={`${item.title}的原创线稿配图`} loading="lazy" onError={event=>{event.currentTarget.style.display="none"}}/></div><div className="archive-meta"><span>{item.type}</span><time>{item.year}</time></div><h3>{item.title}</h3><p className="original">{item.original || "RM ARCHIVE COLLECTION"}</p><p>{item.summary}</p><div className="tagrow">{item.tags.map(t=><span key={t}>#{t}</span>)}</div><button>查看内容 <b>↗</b></button></article>)}</div> }

function MapPanel({data,onSelect}:{data:ArchiveItem[];onSelect:(i:ArchiveItem)=>void}) { return <div className="map-panel"><div className="map-lines" aria-hidden="true"></div><div className="map-label l1">SEOUL</div><div className="map-label l2">USA</div><div className="map-label l3">BUSAN</div>{data.map((item,i)=><button key={item.id} className={`pin p${i+1}`} onClick={()=>onSelect(item)} aria-label={`查看${item.title}`}><span>{i+1}</span><b>{item.place}</b></button>)}</div> }

function Detail({item,onClose}:{item:ArchiveItem;onClose:()=>void}) { return <div className="overlay" role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={onClose}><div className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose} aria-label="关闭">×</button><div className="detail-visual"><span aria-hidden="true">{item.image}</span><img src={`/illustrations/${item.id}.webp`} alt={`${item.title}的原创线稿配图`} onError={event=>{event.currentTarget.style.display="none"}}/><small>ARCHIVE ILLUSTRATION · {item.year}</small></div><div className="detail-body"><div className="detail-kicker">{item.type}</div><h2 id="detail-title">{item.title}</h2><p className="detail-original">{item.original}</p><p className="detail-summary">{item.summary}</p><dl><div><dt>时间</dt><dd>{item.year}</dd></div><div><dt>地区</dt><dd>{item.place || "—"}</dd></div><div><dt>关键词</dt><dd>{item.tags.join(" · ")}</dd></div></dl>{item.sourceUrl && <a className="story-link" href={item.sourceUrl} target="_blank" rel="noreferrer">延伸阅读 ↗</a>}</div></div></div> }
